### ISSUE TITLE
Cannot install using configure, make etc

### ISSUE THREAD

**Issue by sarnobat** [albertz/timidity-macosx#1]
When I `cd` to the root folder and try to run `./configure` there is no binary to execute. So all the `make` commands that follow don't work.

Am I doing something wrong?

**Comment by albertz** [comment]
I guess you need to run automake or autoconf or sth like that.

**Comment by sarnobat** [comment]
I'm not sure how to do that, but I guess that's beyond the scope of this ticket. Thanks for the reply.

**Comment by albertz** [comment]
Just type `automake` or `autoconf`. See their documentation. There are the `ac*` files and `*.am` files which indicate that.
